// Generated by Hexa 2026.1.31 https://hexalang.github.io
// Project: Tofita Build Script
// LICENSE LGPL-3.0-only
;(() => {
	"use strict"
	const $global = typeof(window) === "undefined"? global : window
	if (typeof($global.require) === "undefined") { $global.require = () => {} };
	const selfVersion="undefined";
	const $toIterator = (v) => typeof(v) === "number"? Array(Math.max(v, 0)).keys() : v;
	const ProcessModule = require("process")
	var console_160 = $global.console
	var Map_154 = $global.Map
	function hasOwnProperty(object, name) { return object.hasOwnProperty(name) };
	function btoa(text_394) { return Buffer.from(text_394, 'binary').toString('base64', 0, 1073741824) };
	function atob(base64) { return Buffer.from(base64, 'base64').toString('binary', 0, 1073741824) };
	function packFonts(config_395) {
		const fs_396 = require('fs');
		const chars = JSON.parse(fs_396.readFileSync('..\\include\\fonts\\bitmap\\ASCII.json').toString().trim());
		const charSize = 12;
		const size = 256 * 12;
		const buffer = Buffer.alloc(size);
		{
			let ascii = 0;
			let it = 0;
			while (it < 256) {
				ascii = it;
				it++;
				{
					for (const char of $toIterator(chars)) {
						if (char.code == ascii) {
							let offset = 12 * ascii;
							offset = buffer.writeUInt16LE(char.x, offset);
							offset = buffer.writeUInt16LE(char.y, offset);
							offset = buffer.writeDoubleLE(char.width, offset);
						};
					};
				};
			};
		};
		fs_396.writeFileSync(config_395.tempFolder + '\\BKosmos\\ascii.bin', buffer, 'binary');
	};
	function packAssets(config_397) {
		const folder = config_397.tempFolder + '\\BKosmos';
		const fs_398 = require('fs');
		const assetName = [];
		const assetPath = [];
		const folders = new Map();
		assetName.push('kosmos.exe');
		assetPath.push(folder + '\\kosmos.exe');
		assetName.push('trapeze.sys');
		assetPath.push(folder + '\\trapeze.bin');
		for (const dll of $toIterator(dlls)) {
			assetName.push('C:\\Windows\\System32\\' + dll + '.dll');
			assetPath.push(folder + ('\\' + (dll) + '.64.dll'));
			assetName.push('C:\\Windows\\SysWOW64\\' + dll + '.dll');
			assetPath.push(folder + ('\\' + (dll) + '.32.dll'));
		};
		packFonts(config_397);
		assetName.push('ascii.bin');
		assetPath.push(folder + '\\ascii.bin');
		assetName.push('root/Windows/Fonts/ascii.png');
		assetPath.push('..\\include\\fonts\\bitmap\\ascii.png');
		const addFolderRecursive = (path_399) => { if (fs_398.existsSync(path_399)) {
			const filesList = [];
			fs_398.readdirSync(path_399).forEach((file, index) => {
				const curPath = path_399 + '\\' + file;
				const assetFullName = curPath.substr(18, 1073741824).split('\\').join('/');
				if (fs_398.lstatSync(curPath).isDirectory()) {
					addFolderRecursive(curPath);
					filesList.push(assetFullName.split('/').pop() + '\r');
				} else {
					assetName.push(assetFullName);
					assetPath.push(curPath);
					filesList.push(assetFullName.split('/').pop());
				};
			});
			const folderFullName = path_399.substr(18).split('\\').join('/');
			folders.set(folderFullName + '\r', Buffer.from(filesList.join('\n') + '\n', 'utf16le'));
		} };
		addFolderRecursive('..\\include\\assets\\root');
		addFolderRecursive('..\\include\\assets\\desktop');
		let ramDiskSize = 0;
		for (const asset of $toIterator(assetPath)) {
			ramDiskSize += fs_398.statSync(asset).size;
		};
		let folderCount = 0;
		for (const folder of $toIterator(folders.keys())) {
			ramDiskSize += folders.get(folder).length;
			folderCount++;
		};
		ramDiskSize += 4;
		ramDiskSize += 4;
		ramDiskSize += 4;
		ramDiskSize += 264 * (assetName.length + folderCount);
		ramDiskSize = Math.ceil(ramDiskSize / 4) * 4;
		const buffer_400 = Buffer.alloc(ramDiskSize);
		buffer_400.writeUInt32LE(0, 0);
		buffer_400.writeUInt32LE(ramDiskSize, 4);
		buffer_400.writeUInt32LE(assetName.length + folderCount, 8);
		const assetInfoSize = 264;
		let assetInfoOffset = 12;
		let assetDataOffset = ramDiskSize;
		{
			let i = 0;
			let it_401 = 0;
			let at = assetName.length;
			while (it_401 < at) {
				i = it_401;
				it_401++;
				{
					const asset = assetName[i];
					const path_402 = assetPath[i];
					const assetSize = fs_398.statSync(path_402).size;
					buffer_400.write(asset, assetInfoOffset, 'utf16le');
					buffer_400.writeUInt32LE(assetSize, assetInfoOffset + 256);
					const file_403 = fs_398.readFileSync(path_402);
					assetDataOffset -= assetSize;
					file_403.copy(buffer_400, assetDataOffset);
					buffer_400.writeUInt32LE(assetDataOffset, assetInfoOffset + 260);
					assetInfoOffset += 264;
				};
			};
		};
		for (const folder of $toIterator(folders.keys())) {
			let step = 0;
			const list = folders.get(folder);
			if (step == 0 && list != null) { step = 1 };
			if (step == 1) {
				buffer_400.write(folder, assetInfoOffset, 'utf16le');
				buffer_400.writeUInt32LE(list.length, assetInfoOffset + 256);
				assetDataOffset -= list.length;
				list.copy(buffer_400, assetDataOffset);
				buffer_400.writeUInt32LE(assetDataOffset, assetInfoOffset + 260);
				assetInfoOffset += 264;
			};
		};
		const getChecksum = () => {
			let checksum = 0;
			let i_404 = 1;
			while (i_404 < Math.round(ramDiskSize / 4)) {
				checksum = buffer_400.readUInt32LE(i_404 * 4) & 65535 ^ checksum;
				i_404++;
			};
			return checksum;
		};
		const ramDiskChecksum = getChecksum();
		buffer_400.writeUInt32LE(ramDiskChecksum, 0);
		fs_398.writeFileSync(folder + '\\spin-off\\KOSMOS.DAT', buffer_400, 'binary');
	};
	function deleteFolderRecursive(path_405, noRemoveSelf = false) { if (fs.existsSync(path_405)) {
		fs.readdirSync(path_405).forEach((file, index) => {
			const curPath = path_405 + '\\' + file;
			if (fs.lstatSync(curPath).isDirectory()) { deleteFolderRecursive(curPath, false) } else {
				fs.unlinkSync(curPath);
			};
		});
		if (noRemoveSelf != true) { fs.rmSync(path_405, {recursive:true, force:true}) };
	} };
	function runTasks() {
		const folder_413 = config.tempFolder + '\\BKosmos';
		const begin_414 = Date.now();
		if (cleanupTask) {
			if ((!fs.existsSync(folder_413))) { fs.mkdirSync(folder_413) };
			deleteFolderRecursive(folder_413, true);
			fs.copyFileSync('..\\include\\assets\\tea.ico', folder_413 + '\\icon.ico');
			fs.copyFileSync('desktop.ini', folder_413 + '\\desktop.ini');
			require('child_process').execSync('cmd /c ATTRIB +S ' + folder_413, {stdio:'inherit'});
			const dirs = [path.sep + 'BKosmos', path.sep + 'spin-off', path.sep + 'EFI', path.sep + 'BOOT'];
			let path_415 = config.tempFolder;
			for (const dir of $toIterator(dirs)) {
				path_415 += dir;
				if ((!fs.existsSync(path_415))) { fs.mkdirSync(path_415) };
			};
			const assets = folder_413 + '\\spin-off\\KOSMOS.DAT';
			if (fs.existsSync(assets)) { fs.unlinkSync(assets) };
		};
		const phase1 = [];
		const phase2 = [];
		const phase3 = [];
		if (asmTask) {
			phase1.push('..\\TEAPOT\\nasm-2.14.02\\nasm' + ' -f win64 -o ' + folder_413 + '\\trampoline.o boot\\loader\\trampoline.asm');
			phase1.push('..\\TEAPOT\\nasm-2.14.02\\nasm' + (((debuggie)? (' -g') : '')) + ' -f win64 -o ' + folder_413 + '\\kosmos.asm.obj all.asm');
			phase1.push('..\\TEAPOT\\nasm-2.14.02\\nasm' + ' -f bin -o ' + folder_413 + '\\trapeze.bin devices\\cpu\\trapeze.asm');
			phase1.push('..\\TEAPOT\\nasm-2.14.02\\nasm' + ' -f win64 -o ' + folder_413 + '\\kosmos64.asm.obj dlls\\kosmos64.asm');
			phase1.push('..\\TEAPOT\\nasm-2.14.02\\nasm' + ' -f win32 -o ' + folder_413 + '\\kosmos32.asm.obj dlls\\kosmos32.asm');
		};
		if (efiTask) {
			phase1.push('cmd /c hexa --output-folder ' + config.tempFolder + '/BKosmos boot\\hexa.json');
			let target = 'x86_64-pc-win32-coff';
			{
				const temp_416 = cpuTarget;
				switch (temp_416) {
				case 0: {
					target = 'x86_64-pc-win32-coff'
				} break;
				
				case 1: {
					target = 'aarch64-pc-win32-coff'
				} break;
				
				case 2: {
					target = 'riscv64-pc-win32-coff -mno-relax'
				} break;
				};
			};
			phase2.push(['..\\TEAPOT\\LLVM-14.0.6-2\\bin\\clang.exe ', '-target ' + target + ' -fno-stack-protector', ((useCpp)? ('-x c++ -std=c++2a -fno-rtti -fno-exceptions') : '-x c -std=gnu17'), '-fshort-wchar -mno-red-zone -w', '-fomit-frame-pointer', '-fno-stack-check', '-D versionRolling=' + versionRolling, '-D versionName=\\"' + versionName + '\\"', '-D versionMajor=' + versionMajor, '-D versionMinor=' + versionMinor, '-D versionTag=' + versionTag, '-D HEXA_NO_PLATFORM_INCLUDES=1', '-mno-ms-bitfields -fno-threadsafe-statics', '-Wno-address-of-temporary', '-fshort-wchar -mno-red-zone -O2 -ferror-limit=10', '-mno-sse -mno-avx', ' -c ', config.tempFolder + '/BKosmos/uefi.c', ' -o ', config.tempFolder + '/BKosmos/miniefi.o'].join(' '));
			let efi = 'BOOTX64.EFI';
			if (cpuTarget == 1) { efi = 'BOOTAA64.EFI' } else if (cpuTarget == 2) { efi = 'BOOTRISCV64.EFI' };
			phase3.push(['..\\TEAPOT\\LLVM-14.0.6-2\\bin\\lld-link.exe ', '-subsystem:efi_application -nodefaultlib -dll -entry:efi_main ', config.tempFolder + '/BKosmos/trampoline.o ', config.tempFolder + '/BKosmos/miniefi.o ', ' -out:', config.tempFolder + '/' + 'BKosmos' + '/spin-off/EFI/BOOT/' + efi].join(''));
		};
		if (dllTask) {
			const buildDLLs = (bit, arch) => {
				let i = 0;
				let it = 0;
				let at = dlls.length;
				while (it < at) {
					i = it;
					it++;
					{
						const dllsFolder = ((dlls[i] == 'kosmos32')? ('dlls') : '..\\include\\dll');
						if (bit == '32') { phase1.push('cmd /c hexa --output-folder ' + folder_413 + (' --define bit64=false ' + (dllsFolder) + '\\' + (dlls[i]) + '\\hexa.json --target i386')) } else {
							phase1.push('cmd /c hexa --output-folder ' + folder_413 + (' --define bit64=true ' + (dllsFolder) + '\\' + (dlls[i]) + '\\hexa.json --target default'));
						};
						let asm = ' ';
						if (dlls[i] == 'ntdll' || dlls[i] == 'kosmos32') { asm = folder_413 + ('\\kosmos' + (bit) + '.asm.obj ') };
						const outobj = folder_413 + '\\' + dlls[i] + '.' + bit + '_dll.obj';
						phase2.push(['..\\TEAPOT\\LLVM-14.0.6-2\\bin\\clang.exe ', ('-m' + (bit) + ' -Xclang -flto-visibility-public-std -target ' + (arch) + '-pc-windows-msvc -nostdlib -nodefaultlibs -nostartfiles'), '-fms-compatibility -fms-extensions', '-ffast-math -Wno-incompatible-library-redeclaration -Wno-absolute-value -s -w', '-Wimplicit-function-declaration -O2 -c', '-mtune=nocona -fno-stack-protector -mno-red-zone', '-fno-rtti -fno-exceptions -fvisibility=default', '-fno-stack-check', '-fshort-wchar', '-mno-ms-bitfields -fno-threadsafe-statics', '-ferror-limit=10', ('-Dbit' + (bit) + ''), '-DHEXA_NO_PLATFORM_INCLUDES', '-msse -msse2 -msse3 -mpopcnt -mcx16 -msahf -mprfchw', '-mno-ssse3 -mno-sse4a -mno-sse4.1 -mno-sse4.2 -mno-sse4', '-fwrapv ', ((useCpp)? ('-x c++ -std=c++2a') : '-x c -std=gnu17'), '-fomit-frame-pointer', folder_413 + '\\' + dlls[i] + '.' + bit + '.c', '-o', outobj].join(' '));
						const machine = (((bit == '32'))? ('86') : '64');
						phase3.push(['..\\TEAPOT\\LLVM-14.0.6-2\\bin\\lld-link.exe ', ('/DLL /WX /MACHINE:X' + (machine) + ' '), (() => {
							const result = [];
							const value = deps[i];
							for (const dep of $toIterator(value)) result.push(config.tempFolder + '/' + 'BKosmos' + '/!' + dep + '.' + bit + '.lib ');
							return result;
						})().join(''), outobj + ' ', asm, '/out:', config.tempFolder + '/' + 'BKosmos' + '/' + dlls[i] + '.' + bit + '.dll'].join(''));
					};
				};
			};
			buildDLLs('64', 'x86_64');
			buildDLLs('32', 'i686');
		};
		if (engineTask) {
	// Пропускаем генерацию kosmos.cpp через Hexa, так как файл уже существует
	// phase1.push('cmd /c hexa --output-folder ' + folder_413 + ' hexa.json');
	
	// Копируем существующий kosmos.cpp из src в папку сборки
			const kosmosCppPath = 'kosmos.cpp'; // Файл уже в текущей папке src
			const targetKosmosCppPath = folder_413 + '\\kosmos.cpp';
	
			if (fs.existsSync(kosmosCppPath)) {
				phase1.push('echo [INFO] Используем существующий kosmos.cpp');
				phase1.push('copy "' + kosmosCppPath + '" "' + targetKosmosCppPath + '" /Y >nul');
			} else {
		// Если файл не существует, все равно пропускаем генерацию
				phase1.push('echo [WARNING] Файл kosmos.cpp не найден, но пропускаем генерацию через Hexa');
			}
	
			phase2.push(['..\\TEAPOT\\LLVM-14.0.6-2\\bin\\clang.exe', '-D versionRolling=' + versionRolling, '-D versionName=\\"' + versionName + '\\"', '-D versionMajor=' + versionMajor, '-D versionMinor=' + versionMinor, '-D versionTag=' + versionTag, '-mtune=nocona -fno-stack-protector -fshort-wchar -mno-red-zone ', '-fno-stack-check ', ((debuggie)? ('-fvisibility=default') : '-fvisibility=hidden'), '-Dbit64', '-DHEXA_NO_PLATFORM_INCLUDES', '-fno-rtti -fno-exceptions -ffreestanding ', '-mno-ms-bitfields -fno-threadsafe-statics ', '-msse -msse2 -msse3 -mpopcnt -mcx16 -msahf -mprfchw ', '-mno-ssse3 -mno-sse4a -mno-sse4.1 -mno-sse4.2 -mno-sse4 ', '-m64 -target x86_64-pc-windows-gnu -nostdlib -nodefaultlibs ', '-fno-pic -mcmodel=large ', warn, '-Wno-incompatible-library-redeclaration -Wno-absolute-value -Wimplicit-function-declaration ', '-O2 -fwrapv -fno-strict-aliasing -fno-strict-overflow -mtune=nocona ', '-ffast-math -ferror-limit=10', '-w', ((debuggie)? ('-fno-omit-frame-pointer') : '-fomit-frame-pointer'), '-Wno-address-of-temporary', ((debuggie)? ('-g') : ''), ((useCpp)? ('-x c++ -std=c++2a') : '-x c -std=gnu17'), '-c ' + config.tempFolder + '/BKosmos/kosmos.cpp -o ', config.tempFolder + '/BKosmos/kosmos.obj '].join(' '));
			phase3.push(['..\\TEAPOT\\LLVM-14.0.6-2\\bin\\lld-link.exe ', ((debuggie)? ('/debug:dwarf ') : ''), '/FIXED ', '/WX /MACHINE:X64 /entry:engineMain /SUBSYSTEM:CONSOLE ', '/BASE:0xffff800000000000 ', config.tempFolder + '/BKosmos/kosmos.asm.obj ', config.tempFolder + '/BKosmos/kosmos.obj ', '/out:', config.tempFolder + '/BKosmos/kosmos.exe'].join(''));
			};
		process.stdout.write('[Processing...]\n');
		let currentWave = phase1;
		let busy = 0;
		let maxBusy = 0;
		const evaluate = () => {
			if (busy == 0 && currentWave.length == 0) { if (currentWave == phase1) {
				{
					let i_417 = 0;
					let it_418 = 0;
					let at_419 = dlls.length;
					while (it_418 < at_419) {
						i_417 = it_418;
						it_418++;
						{
							const named = dlls[i_417];
							const gen = (' file %bit %named ' + config.tempFolder + '/BKosmos/!%named.%bit.lib ');
							const names64 = config.tempFolder + '\\' + 'BKosmos' + ('\\' + (named) + '.64.c.dllExport.txt');
							const names32 = config.tempFolder + '\\' + 'BKosmos' + ('\\' + (named) + '.32.c.dllExport.txt');
							phase2.push('..\\TEAPOT\\libgen.exe' + (gen + names64).replaceAll('%named', named).replaceAll('%bit', '64'));
							phase2.push('..\\TEAPOT\\libgen.exe' + (gen + names32).replaceAll('%named', named).replaceAll('%bit', '32'));
						};
					};
				};
				currentWave = phase2;
			} else if (currentWave == phase2) { currentWave = phase3 } else if (currentWave == phase3) { currentWave = [] } };
			const cmd = currentWave.shift();
			{
				let step = 0;
				const cmd_420 = cmd;
				if (step == 0 && cmd_420 != null) { step = 1 };
				if (step == 1) {
					child_process.exec(cmd_420, (error, stdout, stderr) => {
						if (error != null) {
							console.log('[Build error] ' + cmd_420);
							if ('' != '' + stdout) { console.log(stdout) };
							if ('' != '' + stderr) { console.log(stderr) };
							process.exitCode = 123;
							process.stdout.once('drain', () => { process.exit(123) });
							return;
						};
						if ('' != '' + stdout) { console.log(stdout) };
						busy--;
						evaluate();
					});
					busy++;
					if (busy > maxBusy) { maxBusy = busy };
					if (currentWave.length != 0) { evaluate() };
				} else if (busy == 0) {
					if (ramDiskTask) { packAssets(config) };
					if (isoTask) {
						fs.copyFileSync('..\\include\\assets\\autorun.ico', folder_413 + '\\spin-off\\autorun.ico');
						fs.copyFileSync('..\\include\\assets\\autorun.inf', folder_413 + '\\spin-off\\autorun.inf');
						fs.copyFileSync('LICENSE', folder_413 + '\\spin-off\\LICENSE.txt');
						fs.writeFileSync(folder_413 + '\\spin-off\\version.txt', versionName);
						let efi_421 = 'BOOTX64.EFI';
						if (cpuTarget == 1) { efi_421 = 'BOOTAA64.EFI' } else if (cpuTarget == 2) { efi_421 = 'BOOTRISCV64.EFI' };
						if ((secureBoot) && (cpuTarget == 0)) {
							const bootPath = folder_413 + '\\spin-off\\EFI\\BOOT\\';
							if (fs.existsSync(bootPath + 'grubx64.efi')) { fs.unlinkSync(bootPath + 'grubx64.efi') };
							fs.copyFileSync(bootPath + 'BOOTX64.EFI', bootPath + 'grubx64.efi');
							if (fs.existsSync(bootPath + 'BOOTX64.EFI')) { fs.unlinkSync(bootPath + 'BOOTX64.EFI') };
							fs.copyFileSync('..\\TEAPOT\\blobs\\shimx64.efi', bootPath + 'BOOTX64.EFI');
						};
						fs.copyFileSync('..\\TEAPOT\\mtools\\disk-template.img', folder_413 + '\\DISK.IMG');
						for (const cmd of ['..\\TEAPOT\\mtools\\mmd.exe' + ' -i ' + folder_413 + '\\DISK.IMG ::/EFI', '..\\TEAPOT\\mtools\\mmd.exe' + ' -i ' + folder_413 + '\\DISK.IMG ::/EFI/BOOT', '..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG ' + folder_413 + '\\spin-off\\KOSMOS.DAT ::/KOSMOS.DAT', '..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG ' + folder_413 + '\\spin-off\\EFI\\BOOT\\' + efi_421 + ' ::/EFI/BOOT/' + efi_421, '..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG ' + folder_413 + '\\spin-off\\version.txt ::/version.txt', '..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG LICENSE ::/LICENSE.txt', '..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG ..\\include\\assets\\autorun.ico ::/autorun.ico', '..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG ..\\include\\assets\\autorun.inf ::/autorun.inf']) {
							child_process.execSync(cmd, {stdio:'inherit'});
						};
						if ((secureBoot) && (cpuTarget == 0)) { child_process.execSync('..\\TEAPOT\\mtools\\mcopy.exe' + ' -i ' + folder_413 + '\\DISK.IMG ' + folder_413 + '\\spin-off\\EFI\\BOOT\\grubx64.efi ::/EFI/BOOT/grubx64.efi', {stdio:'inherit'}) };
						fs.copyFileSync(folder_413 + '\\DISK.IMG', folder_413 + '\\spin-off\\DISK.IMG');
						const path_422 = '/cygdrive/' + folder_413.split(':').join('');
						const efi_423 = '0xef';
						child_process.execSync(['..\\TEAPOT\\xorriso-1.5.2\\xorriso.exe', ('-as mkisofs -o ' + (path_422) + '/kosmos.iso -iso-level 3'), ('-V GTOS ' + (path_422) + '/spin-off'), ('-append_partition 2 ' + '0xef' + ' ' + (path_422) + '/DISK.IMG'), '-e --interval:appended_partition_2:all::', '-no-emul-boot'].join(' '), {stdio:'inherit'});
					};
					if ((!debuggie)) {
						const path_424 = folder_413;
						fs.readdirSync(path_424).forEach((file_425, index_426) => { if (file_425.endsWith('.c')) { fs.unlinkSync(path_424 + '\\' + file_425) } });
					};
					console.log(('[All tasks finished in ' + (Date.now() - begin_414) + ' ms, upto ' + (maxBusy) + ' parallel tasks performed]'));
					process.stdout.once('drain', () => { process.exit(0) });
				};
			};
		};
		evaluate();
	};
	var bFolder = 'BKosmos'
	var tea = '\\BKosmos'
	var dlls = ['ntdll', 'kernel32', 'gdi32', 'user32', 'comctl32', 'shell32', 'msvcrt', 'advapi32', 'kosmos32']
	var deps = [[], ['ntdll'], ['ntdll', 'kernel32'], ['ntdll', 'kernel32', 'gdi32'], ['ntdll', 'kernel32'], ['ntdll', 'kernel32'], ['ntdll', 'kernel32'], ['ntdll', 'kernel32'], []]
	var fs = require('fs')
	var path = require('path')
	var child_process = require('child_process')
	var cleanupTask = false
	var asmTask = false
	var efiTask = false
	var dllTask = false
	var engineTask = false
	var ramDiskTask = false
	var isoTask = false
	var useCpp = false
	var secureBoot = false
	var cpuTarget = 0
	var debuggie = false
	var strict = false
	var config = JSON.parse(fs.readFileSync('config.json').toString())
	var tasks = process.argv.slice(0, 1073741824)
	var llvm = 'LLVM-14.0.6-2'
	var teapot = '..\\TEAPOT'
	var nasm = '..\\TEAPOT\\nasm-2.14.02\\nasm'
	var clang = '..\\TEAPOT\\LLVM-14.0.6-2\\bin\\clang.exe'
	var link = '..\\TEAPOT\\LLVM-14.0.6-2\\bin\\lld-link.exe'
	var xorriso = '..\\TEAPOT\\xorriso-1.5.2\\xorriso.exe'
	var mmd = '..\\TEAPOT\\mtools\\mmd.exe'
	var mcopy = '..\\TEAPOT\\mtools\\mcopy.exe'
	var libgen = '..\\TEAPOT\\libgen.exe'
	var warn = ((config.warnings)? (['-Wall', '-Wextra', '-Werror', '-ferror-limit=1000'].join(' ')) : '-w') + ' '
	var enabledFeatures = '-msse -msse2 -msse3 -mpopcnt -mcx16 -msahf -mprfchw '
	var disabledFeatures = '-mno-ssse3 -mno-sse4a -mno-sse4.1 -mno-sse4.2 -mno-sse4 '
	var optimizationFeatures = '-O2 -fwrapv -fno-strict-aliasing -fno-strict-overflow -mtune=nocona '
	var definedBehavior = '-fwrapv '
	var today = new Date()
	var month = today.getMonth() + 1
	var versionMajor = today.getFullYear()
	var versionMinor = month
	var versionTag = today.getDate()
	var versionRolling = versionMajor * 10000 + versionMinor * 100 + versionTag
	var versionName = today.getFullYear() + '.' + month + '.' + today.getDate()
	{
		{
			tasks.shift();
			tasks.shift();
			if (tasks.length == 0) { console.log('No tasks defined') };
			console.log(('[Tasks: ' + (tasks.join(', ')) + ']'));
			for (const folder of ['include', 'Teapot']) {
				if ((!fs.existsSync('..\\' + folder))) {
					console.error(('Folder ..\\' + (folder) + ' is not present. You should download this repo from GitHub.'));
					process.exit(123);
					break;
				};
			};
			for (const task of ['tasks']) {
				const folder = config.tempFolder + '\\BKosmos';
				{
					const temp = task;
					switch (temp) {
					case 'clang-format': {
						{
							const clang_406 = '..\\TEAPOT\\LLVM-14.0.6-2\\bin\\clang-format';
							const files = [];
							const formatFolderRecursive = (path_407) => { if (fs.existsSync(path_407)) { fs.readdirSync(path_407).forEach((file_408, index_409) => {
								const curPath_410 = path_407 + '\\' + file_408;
								if (fs.lstatSync(curPath_410).isDirectory()) { formatFolderRecursive(curPath_410) } else {
									if ((curPath_410.indexOf('external\\', 0) == (-1)) && (curPath_410.endsWith('.c') || curPath_410.endsWith('.hpp'))) { files.push(curPath_410) };
								};
							}) } };
							formatFolderRecursive('.');
							require('child_process').execSync('..\\TEAPOT\\LLVM-14.0.6-2\\bin\\clang-format' + ' -i -style=file ' + files.join(' '), {stdio:'inherit'});
							console.log('clang-format ' + files.length + ' files');
						}
					} break;
					
					default: 
					{
					}
					};
				};
			};
			for (const task of $toIterator(tasks)) {
				const folder_411 = config.tempFolder + '\\BKosmos';
				const begin = Date.now();
				{
					const temp_412 = task;
					switch (temp_412) {
					case 'help': {
						{
						}
					} break;
					
					case 'ci': {
						{
						}
					} break;
					
					case 'debug': {
						{
							console.log('[Debug mode is ON]');
							debuggie = true;
						}
					} break;
					
					case 'strict': {
						{
							console.log('[Strict mode is ON]');
							strict = true;
						}
					} break;
					
					case 'verbose': {
						{
						}
					} break;
					
					case 'experimental': {
						{
						}
					} break;
					
					case 'init-or-clean': {
						cleanupTask = true
					} break;
					
					case 'asm': {
						asmTask = true
					} break;
					
					case 'efi': {
						efiTask = true
					} break;
					
					case 'dll': {
						dllTask = true
					} break;
					
					case 'engine': {
						engineTask = true
					} break;
					
					case 'ramdisk': {
						ramDiskTask = true
					} break;
					
					case 'iso': {
						isoTask = true
					} break;
					
					case 'risc64': {
						cpuTarget = 2
					} break;
					
				 case 'arm64': {
						cpuTarget = 1
					} break;
					
					case 'cxx': {
						useCpp = true
					} break;
					
					case 'secure-boot': {
						secureBoot = true
					} break;
					
					default: 
					{
						console.log(('[Unknown task ' + (task) + ']'));
						process.exit(0);
					}
					};
				};
			};
			runTasks();
		}
	}
})();